// Generated by scripts/prepare-osm-data.py. Do not edit by hand.
export const PENSACOLA_OSM_CORRIDOR_METADATA = {
  "source": "OpenStreetMap via Overpass API",
  "note": "Optional road corridor extract for Metro Pensacola road snapping.",
  "highwayFilter": "motorway|trunk|primary|secondary|tertiary|unclassified|residential|living_street|service",
  "coverage": {
    "type": "osm-relation-areas",
    "counties": {
      "Escambia County": 1210737,
      "Santa Rosa County": 1210706
    }
  },
  "featureCount": 37930
} as const;
