#!/usr/bin/env python3
"""Fetch a Metro Pensacola OSM road corridor extract from Overpass.

The MVP uses live OSM raster tiles for the visible basemap. This script creates
an optional static GeoJSON extract that supports road-following route snapping,
corridor inspection, and offline QA layers.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import urllib.parse
import urllib.request
from typing import Any


DEFAULT_COUNTIES = {
    "Escambia County": 1210737,
    "Santa Rosa County": 1210706,
}
HIGHWAY_FILTER = "motorway|trunk|primary|secondary|tertiary|unclassified|residential|living_street|service"
OVERPASS_URLS = [
    "https://overpass-api.de/api/interpreter",
    "https://overpass.kumi.systems/api/interpreter",
    "https://overpass.openstreetmap.ru/api/interpreter",
]


def parse_bbox(value: str) -> tuple[float, float, float, float]:
    west, south, east, north = [float(part.strip()) for part in value.split(",")]
    return west, south, east, north


def area_id_for_relation(relation_id: int) -> int:
    return 3_600_000_000 + relation_id


def area_alias(name: str) -> str:
    return "".join(character for character in name.title() if character.isalnum())


def build_area_query(counties: dict[str, int]) -> str:
    area_definitions = "\n".join(
        f"    area(id:{area_id_for_relation(relation_id)})->.{area_alias(county_name)};"
        for county_name, relation_id in counties.items()
    )
    road_queries = "\n".join(
        f'      way["highway"~"{HIGHWAY_FILTER}"]["service"!~"driveway|parking_aisle|drive-through"](area.{area_alias(county_name)});'
        for county_name in counties
    )
    return f"""
    [out:json][timeout:180];
{area_definitions}
    (
{road_queries}
    );
    (._;>;);
    out body;
    """


def build_bbox_query(bbox: tuple[float, float, float, float]) -> str:
    west, south, east, north = bbox
    overpass_bbox = f"{south},{west},{north},{east}"
    return f"""
    [out:json][timeout:180];
    (
      way["highway"~"{HIGHWAY_FILTER}"]["service"!~"driveway|parking_aisle|drive-through"]({overpass_bbox});
    );
    (._;>;);
    out body;
    """


def fetch_overpass(query: str) -> dict[str, Any]:
    data = urllib.parse.urlencode({"data": query}).encode()
    last_error: Exception | None = None
    for url in OVERPASS_URLS:
        request = urllib.request.Request(
            url,
            data=data,
            method="POST",
            headers={"User-Agent": "MetroPensacola/0.1"},
        )
        try:
            with urllib.request.urlopen(request, timeout=120) as response:
                return json.loads(response.read().decode("utf-8"))
        except Exception as exc:
            last_error = exc
    raise RuntimeError(f"All Overpass endpoints failed: {last_error}")


def parse_counties(value: str) -> dict[str, int]:
    counties: dict[str, int] = {}
    for part in value.split(","):
        if not part.strip():
            continue
        name, relation_id = [piece.strip() for piece in part.split(":", 1)]
        counties[name] = int(relation_id)
    return counties


def osm_to_geojson(osm: dict[str, Any], metadata: dict[str, Any]) -> dict[str, Any]:
    nodes: dict[int, tuple[float, float]] = {}
    features: list[dict[str, Any]] = []

    for element in osm.get("elements", []):
        if element.get("type") == "node":
            nodes[int(element["id"])] = (round(float(element["lon"]), 6), round(float(element["lat"]), 6))

    for element in osm.get("elements", []):
        if element.get("type") != "way":
            continue
        coordinates = [nodes[node_id] for node_id in element.get("nodes", []) if node_id in nodes]
        if len(coordinates) < 2:
            continue
        tags = element.get("tags", {})
        features.append(
            {
                "type": "Feature",
                "properties": {
                    "osm_id": element.get("id"),
                    "name": tags.get("name"),
                    "highway": tags.get("highway"),
                    "railway": tags.get("railway"),
                    "public_transport": tags.get("public_transport"),
                    "maxspeed": tags.get("maxspeed"),
                },
                "geometry": {"type": "LineString", "coordinates": coordinates},
            }
        )

    return {
        "type": "FeatureCollection",
        "metadata": {
            "source": "OpenStreetMap via Overpass API",
            "note": "Optional road corridor extract for Metro Pensacola road snapping.",
            "highwayFilter": HIGHWAY_FILTER,
            **metadata,
        },
        "features": features,
    }


def write_metadata_typescript(metadata: dict[str, Any], output: pathlib.Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "\n".join(
            [
                "// Generated by scripts/prepare-osm-data.py. Do not edit by hand.",
                f"export const PENSACOLA_OSM_CORRIDOR_METADATA = {json.dumps(metadata, indent=2)} as const;",
                "",
            ]
        ),
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--bbox",
        default=None,
        help="Optional west,south,east,north clip. If omitted, the default county relation areas are used.",
    )
    parser.add_argument(
        "--counties",
        default=",".join(f"{name}:{relation_id}" for name, relation_id in DEFAULT_COUNTIES.items()),
        help="Comma-separated county name:OSM relation ID pairs. Defaults to Escambia and Santa Rosa.",
    )
    parser.add_argument("--out", default="public/data/pensacola/osm-corridors.geojson")
    parser.add_argument("--metadata-out", default="src/data/pensacola/osmCorridorsMetadata.ts")
    args = parser.parse_args()

    bbox = parse_bbox(args.bbox) if args.bbox else None
    counties = parse_counties(args.counties)
    query = build_bbox_query(bbox) if bbox else build_area_query(counties)
    osm = fetch_overpass(query)
    geojson = osm_to_geojson(
        osm,
        {
            "coverage": (
                {
                    "type": "bbox",
                    "west": bbox[0],
                    "south": bbox[1],
                    "east": bbox[2],
                    "north": bbox[3],
                }
                if bbox
                else {
                    "type": "osm-relation-areas",
                    "counties": counties,
                }
            )
        },
    )
    geojson["metadata"]["featureCount"] = len(geojson["features"])

    out_path = pathlib.Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(geojson, indent=2), encoding="utf-8")
    write_metadata_typescript(geojson["metadata"], pathlib.Path(args.metadata_out))
    print(f"Wrote {len(geojson['features'])} OSM corridor features to {out_path}")


if __name__ == "__main__":
    main()
